kind: pipeline
name: default
type: docker

steps:

  - name: Build Documentation
    image: gradle:jdk8
    volumes:
      - name: gradle
        path: /home/gradle/.gradle
    commands:
      - ./gradlew groovyDoc
      - git clone --depth=1 https://$${GITHUB_USERNAME}:$${GITHUB_PUSH_TOKEN}@github.com/devsoap/docs.git build/repo/docs
      - cp -R build/docs/groovydoc build/repo/docs/docs/_fn_gradle_plugin_api
      - cd build/repo/docs
      - git checkout -b fn-gradle-plugin/$${ORG_GRADLE_PROJECT_BUILD_VERSION}
      - git add docs/_fn_gradle_plugin_api
      - git commit -m 'Update API documentation for FN Gradle Plugin $${ORG_GRADLE_PROJECT_BUILD_VERSION}'
      - git push origin fn-gradle-plugin/$${ORG_GRADLE_PROJECT_BUILD_VERSION}
    environment:
      ORG_GRADLE_PROJECT_BUILD_VERSION: 0.0.1
      GITHUB_USERNAME:
        from_secret: GITHUB_USERNAME
      GITHUB_PUSH_TOKEN:
        from_secret: GITHUB_PUSH_TOKEN

  - name: Cleanup
    image: gradle:jdk8
    volumes:
      - name: gradle
        path: /home/gradle/.gradle
    commands:
      - rm -rf /tmp/docs
      - ./gradlew clean
      - ./gradlew --stop
    environment:
      ORG_GRADLE_PROJECT_BUILD_VERSION: ${DRONE_TAG}

volumes:
  - name: gradle
    host:
      path: /tmp/drone/gradle